spring.application.name=Hormix


#Info general DB
spring.datasource.url=jdbc:h2:file:/app/data/hormix_bd
spring.datasource.username=sa
spring.datasource.password=

#Activacion h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Activacion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080